language: python
python:
  - "2.7"
install: "pip install -r web/requirements.txt"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/web/src
  - export PATH=$PATH:$(pwd)/web/bin
  - cd web/
script: run_tests
