gofetch:
  build: gofetch/
  links:
    - db
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=0902e2018e3fbd0e6
    - PSQL_TRUST_LOCALNET=true
nginx:
  build: nginx/
  ports:
    - "80:80"
  volumes:
    - nginx/static:/usr/share/nginx/html
  links:
    - api
api:
  build: api/
  volumes:
    - /Users/smotko/webdev/wave-watcher/gofetch:/go/gofetch
  links:
    - db
  ports:
    - "5000:5000"
